using System;
using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    public class Product_FeatureMetaData
    {
        [Key]
        public int PF_ID { get; set; }

        [Display(Name = "مقدار")]
        [Required(ErrorMessage = "لطفن {0} را وارد کنید")]
        public string Value { get; set; }

        [Display(Name = "ویژگی")]
        [Required(ErrorMessage = "لطفن {0} را وارد کنید")]
        public Nullable<int> FeatureID { get; set; }

        [Display(Name = "محصول")]
        [Required(ErrorMessage = "لطفن {0} را وارد کنید")]
        public Nullable<int> ProductID { get; set; }
    }
}