using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace DataLayer
{
    public class Product_CommentsMetaData
    {
        [Key]
        public int ProductCommentID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int ProductID { get; set; }

        [Display(Name = "نام کاربری")]
        [Required(ErrorMessage = "لطفن {0} خود را وارد کنید")]
        public string UserName { get; set; }

        [Display(Name = "ایمیل")]
        //[DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "فرمت ایمیل را به درستی وارد نمایید")]
        [Required(ErrorMessage = "لطفن {0} خود را وارد کنید")]
        public string Email { get; set; }

        [Display(Name = "وب سایت")]
        public string WebSite { get; set; }

        [Display(Name = "نظر")]
        [Required(ErrorMessage = "لطفن {0} خود را وارد کنید")]
        public string Commnet { get; set; }

        [Display(Name = "تاریخ ایجاد")]
        public System.DateTime CreateDate { get; set; }
    }
}