using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    public class ProductsMetaData
    {
        [Key]
        public int ProductID { get; set; }

        [Display(Name ="عنوان")]
        [Required(ErrorMessage ="لطفن {0} را وارد کنید")]
        [MaxLength(350)]
        public string Title { get; set; }

        [Display(Name ="توضیح مختصر")]
        [Required(ErrorMessage = "لطفن {0} را وارد کنید")]
        [MaxLength(500)]
        [DataType(DataType.MultilineText)]
        public string ShortDescription { get; set; }

        [Display(Name = "متن")]
        [Required(ErrorMessage  = "لطفن {0} را وارد کنید")]
        [DataType(DataType.MultilineText)]
        [AllowHtml]//برای فرستادن درخواست اچ تی ام ادیتور به کنترلر 
        public string Text { get; set; }

        [Display(Name = "قیمت")]
        [Required(ErrorMessage = "لطفن {0} را وارد کنید")]
        public int Price { get; set; }

        [Display(Name = "تصویر")]
        public string ImageName { get; set; }

        [Display(Name = "تاریخ ایجاد")]
        [DisplayFormat(DataFormatString ="{0: yyyy/mm/dd}")]
        public System.DateTime CreateDate { get; set; }
    }
}